{{- if not (empty .Values.conf.ca_cert) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "k8s-keystone-auth.fullname" . }}-ca
  labels:
    {{- include "k8s-keystone-auth.labels" . | nindent 4 }}
stringData:
  cloud_ca.crt: |
{{ .Values.conf.ca_cert | indent 4 }}
{{- end }}
