name: release-please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@a02a34c4d625f9be7cb89156071d8567266a2445 # v4.2.0
        id: release
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        if: ${{ steps.release.outputs.release_created }}
      - name: Build package (x86_64)
        if: ${{ steps.release.outputs.release_created }}
        uses: PyO3/maturin-action@86b9d133d34bc1b40018696f782949dac11bd380 # v1.49.4
        with:
          command: publish
          args: --non-interactive --skip-existing
          manylinux: '2_28'
          target: x86_64
      - name: Build package (aarch64)
        if: ${{ steps.release.outputs.release_created }}
        uses: PyO3/maturin-action@86b9d133d34bc1b40018696f782949dac11bd380 # v1.49.4
        with:
          command: publish
          args: --non-interactive --skip-existing
          manylinux: '2_28'
          target: aarch64
